# Generated by Django 4.2 on 2024-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/pixlr-bg-result_9.png', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
