# Generated by Django 5.0.2 on 2024-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_blog_created_at_alter_blog_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
