# Generated by Django 4.2 on 2024-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('Опубликовано', 'published'), ('Не опубликовано', 'unpublished')], default='Не опубликовано', max_length=20, verbose_name='Статус'),
        ),
    ]
